### ISSUE TITLE
question abouts seed nodes and deamon

### ISSUE THREAD

**Issue by devnasser** [FndNur1Labs/DirhamCli#97]
hey FndNur1Labs
thank you very much for responding on my question in cryptonotefunation project.
right now i do compiling and testing many versions of this project in my VPSs (cryptonote original code, bytecoin based code, monero... etc)., but im still confused about seed nodes and deamon !
what is exactly the difference !?
for exemple, in this project (DirhamCli) you put one server address in the seed nodes:

but, when take a look at monero we find two files, the first is
https://github.com/monero-project/monero/blob/master/src/p2p/net_node.h
the seed nodes are:
const std::vector<std::string> m_seed_nodes_list =
    { "seeds.moneroseeds.se"
    , "seeds.moneroseeds.ae.org"
    , "seeds.moneroseeds.ch"
    , "seeds.moneroseeds.li"
};
line 126
and the second is:
https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl
here, we find node_server like that:
full_addrs.insert("107.152.130.98:18080");
      full_addrs.insert("212.83.175.67:18080");
      full_addrs.insert("5.9.100.248:18080");
full_addrs.insert("163.172.182.165:18080");

(servers for testnet and others if not, look at line: 375)..
but, lets take another project forked from moner.. example: electroneum
the first file contain monero seed nodes !!!!, look at:
https://github.com/electroneum/electroneum/blob/master/src/p2p/net_node.h

but the second file, contain electroneum servers:
https://github.com/electroneum/electroneum/blob/master/src/p2p/net_node.inl

can you explain this please?
thank you in advance :)

**Comment by FndNur1Labs** [comment]
the different they used single nodes where they said simple way. but if you
take a look why bytecoin keep 2 seed?that mean you can HF, Secure and other
stuff. actually i wanna implement multinodes system where secure can linked
with accout, balance,etc and log used for client. where place we just see
information. the main seed is protected on cloud with decentralize system.
just for people used it. monero secure?im not sure since they used 1 seed
type. i prefer multi seed when hacker is low chance attack.;)

bytecoin need run 2 nodes and monero didn't the problem if main seed
destroy. can't reproduce new block~

**Comment by devnasser** [comment]
great explanation... thanks a lot.
so, ill compile your coin (dirhamcli) and monero to compare. i already compile monero but just for test (without change thier seed) and compile bytecoin with 2 seed nodes and working fine.
ill come back to you in another issue ticket.
thanks again.

**Comment by FndNur1Labs** [comment]
no problem xD

**Comment by FndNur1Labs** [comment]
they have many seed for security purposes~you can add on config ;)
